Algoritmo "Comando de atribuição (preço total)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Tutor       : Oziel
// Página      : 37
// Autor(a)    : Tássia Melo
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
Preco_unit, preco_total: real
Quantidade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Preco_unit <- 5.0
Quantidade <- 10
Preco_total<- Preco_unit * Quantidade
Escreva (Preco_total)

Fimalgoritmo