Algoritmo "Comando de entrada de dados (preço total)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Tutor       : Oziel
// Página      : 38
// Autor(a)    : Tássia Melo
// Data atual  : 07/04/2022
Var
// Seção de Declarações das variáveis 
Preco_unit, preco_total: real
Quantidade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Digite o preço unitário: ")
Leia (Preco_unit)
Escreva ("Digite a quantidade de produtos: ")
Leia (Quantidade)
Preco_total <- Preco_unit * Quantidade
Escreva (Preco_total)

Fimalgoritmo