Algoritmo "Faça-para(Seja otimista!)"
// Disciplina   : [Linguagem e Lógica de Programação]
// Tutor       : Oziel
// Página      : 53
// Autor(a)    : Tássia Melo
// Data atual  : 08/04/2022
Var
// Seção de Declarações das variáveis
i : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Para i de 1 até 100 faca
Escreval("Seja otimista e vença na vida!")
fimpara

Fimalgoritmo